/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmojiConfig {
  'accessory' : string,
  'expression' : string,
  'name' : string,
  'color' : string,
  'baseShape' : string,
  'eyeStyle' : string,
  'mouthStyle' : string,
}
export interface _SERVICE {
  'deleteEmoji' : ActorMethod<[bigint], undefined>,
  'getAllEmojiConfigs' : ActorMethod<[], Array<EmojiConfig>>,
  'getEmoji' : ActorMethod<[bigint], EmojiConfig>,
  'saveEmoji' : ActorMethod<[EmojiConfig], bigint>,
  'seedSampleEmojis' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];