/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmojiConfig = IDL.Record({
  'accessory' : IDL.Text,
  'expression' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'baseShape' : IDL.Text,
  'eyeStyle' : IDL.Text,
  'mouthStyle' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteEmoji' : IDL.Func([IDL.Nat], [], []),
  'getAllEmojiConfigs' : IDL.Func([], [IDL.Vec(EmojiConfig)], ['query']),
  'getEmoji' : IDL.Func([IDL.Nat], [EmojiConfig], ['query']),
  'saveEmoji' : IDL.Func([EmojiConfig], [IDL.Nat], []),
  'seedSampleEmojis' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmojiConfig = IDL.Record({
    'accessory' : IDL.Text,
    'expression' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'baseShape' : IDL.Text,
    'eyeStyle' : IDL.Text,
    'mouthStyle' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteEmoji' : IDL.Func([IDL.Nat], [], []),
    'getAllEmojiConfigs' : IDL.Func([], [IDL.Vec(EmojiConfig)], ['query']),
    'getEmoji' : IDL.Func([IDL.Nat], [EmojiConfig], ['query']),
    'saveEmoji' : IDL.Func([EmojiConfig], [IDL.Nat], []),
    'seedSampleEmojis' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };